build.sbt
project/build.properties
project/plugins.sbt

This reverts commit 6b252eeeeadf06b79c2d880bbec79ab6d35550f4.

Revert "ECC-758 upgrading sbt > 1.5"

---

build.sbt
project/build.properties
project/plugins.sbt

This reverts commit a4a51719d485cb7954c8f47acd8f5851579c23ed.

Revert "Revert "ECC-758 upgrading sbt > 1.5""

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/connector/UpdateCustomsDataStoreConnector.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/models/events/CustomDataStoreUpdate.scala
test/integration/UpdateCustomsDataStoreConnectorSpec.scala

CustomDataStoreUpdate got lost in revert commit to try and track down build issues... Restored plus integration test.

ECC-1232: Added back CustomDataStoreUpdate event lost in revert

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/connector/SubscriptionStatusConnector.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/ConfirmContactDetailsController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/UserLocationController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/models/events/SubscriptionStatusSubmitted.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/services/RegistrationConfirmService.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/services/SubscriptionStatusService.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/services/UserGroupIdSubscriptionStatusCheckService.scala
test/integration/SubscriptionStatusConnectorSpec.scala
test/unit/controllers/ConfirmContactDetailsControllerSpec.scala
test/unit/controllers/EmailControllerSpec.scala
test/unit/controllers/UserLocationControllerSpec.scala
test/unit/models/events/SubscriptionStatusSubmittedSpec.scala
test/unit/services/RegistrationConfirmServiceSpec.scala
test/unit/services/SubscriptionStatusServiceSpec.scala
test/unit/services/UserGroupIdSubscriptionStatusCheckServiceSpec.scala

Change lost in revert in attempt to solve build issues... Now restored...

ECC-1232: Add service to SubscriptionStatusSubmitted event

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/views/start.scala.html

Moved content to above the start now button

ECC-1320: Content placed after "Start now" button

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/views/contact_details.scala.html
test/common/pages/subscription/SubscriptionContactDetailsPage.scala

The text was not a hint and therefore was styled wrong, I have removed that styling so we don't get the issue where hint text is not associated with any fields

ECC-1324: Hint text not associated with fields

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/VatRegisteredUkController.scala
test/unit/controllers/VatRegisteredUkSubscriptionControllerSpec.scala

Not to be merged until audit is complete

ECC-1165: Remove cache upon selecting no to VAT question

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/NameIdOrganisationController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/match_name_id_organisation.scala.html
test/unit/controllers/NameUtrOrganisationControllerSpec.scala

Service Type had wrong string value... Magic strings used all over the place :)

ECC-1444: Fix company journey validation and utr lookup url

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/forms/FormValidation.scala

Added GB country code to enforce mandatory postcode on contact details screen. Also added the check for when no country code is supplied

ECC-1445 - made postcode mandatory for UK addresses

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/views/email/verify_your_email.scala.html
conf/messages.cy
conf/messages.en

https://jira.tools.tax.service.gov.uk/browse/ECC-1513

ECC-1513 add missing paragraph

---

conf/application.conf

ARS-454 Enable advance valuation ruling

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/VatDetailsController.scala
test/unit/controllers/VatDetailsControllerSpec.scala

Instead of adding a feature flag I have called the other controller as this will be simpler to clean up in the future when we have an API which works for our requirements.

Remove vat verification option

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/ConfirmContactDetailsController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/DateOfVatRegistrationController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/RowIndividualNameDateOfBirthController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/SicCodeController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/SixLineAddressController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/SubscriptionFlowManager.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/controllers/VatDetailsController.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/domain/registration/UserLocation.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/domain/subscription/SubscriptionDetails.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/forms/FormUtils.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/forms/MatchingForms.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/forms/SubscriptionForm.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/models/events/RegistrationDisplay.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/services/Save4LaterService.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/services/SubscriptionBusinessService.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/services/cache/RequestSessionData.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/services/cache/sessionCache.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/services/countries/Countries.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/services/mapping/CdsToEtmpOrganisationType.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/six_line_address.scala.html
test/unit/controllers/CdsErrorHandlerSpec.scala
test/unit/controllers/CheckYourDetailsRegisterControllerSpec.scala
test/unit/controllers/ConfirmContactDetailsControllerSpec.scala
test/unit/controllers/ContactAddressControllerSpec.scala
test/unit/controllers/SixLineAddressControllerSpec.scala
test/unit/views/SixLineAddressSpec.scala

In addition to making IOM 6 line address form pre-populated, unused imports resulting in warnings have been removed to clean up the code

ECC-1735 - Make IOM country pre-populated

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/views/standalone_subscription_outcome.scala.html
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/subscription_outcome.scala.html

Changing wrong usage of `H2` heading -  https://jira.tools.tax.service.gov.uk/browse/ECC-1892

ECC-1892 changing h2 headings

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/views/helpers/h2.scala.html
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/match_name_id_organisation.scala.html
conf/messages.cy
conf/messages.en

amending content on a company page

ECC-1915 amending content on a company page

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/views/how_can_we_identify_you.scala.html

Fix also applied to Subscription https://github.com/hmrc/eori-common-component-frontend/pull/506

ECC-1923: Fix for validation error message not linking to field

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/views/contact_details.scala.html
conf/messages.cy
conf/messages.en

ECC-1965 restructured the contact details page and removed the 'p' tag 

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/views/helpers/linkWithPreTextAndPostText.scala.html
app/uk/gov/hmrc/eoricommoncomponent/frontend/views/vat_details.scala.html
test/unit/views/VatDetailsViewSpec.scala

also added tests for vat_details view

ECC-2089 changed order of error messages

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/domain/messaging/subscription/SubscriptionCreateRequest.scala
app/uk/gov/hmrc/eoricommoncomponent/frontend/services/SubscriptionService.scala
test/unit/domain/messaging/SubscriptionCreateRequestSpec.scala
test/unit/services/SubscriptionServiceSpec.scala

- redirect to start page if required data is missing
- clean-up unused model constructor methods

ECC-2082 redirect on missing data in cache

---

app/uk/gov/hmrc/eoricommoncomponent/frontend/services/mapping/RegistrationDetailsCreator.scala

Remove additional logging, as issue is now fixed

Remove additional logging, as issue is now fixed
